package:
  name: elektronn
  version: 1.0.1

source:
    git_url: https://github.com/ELEKTRONN/ELEKTRONN.git
    git_rev: v1.0.1

requirements:
  build:
    - python 2.7*
    - setuptools
    - cython
    - theano
    - h5py
    - matplotlib

  run:
    - python 2.7*
    - theano
    - h5py
    - matplotlib

about:
  home: http://www.elektronn.org/
  license: GPLv3
  license_file: LICENSE.txt
