package:
  name: elektronn
  version: 0.1.0

source:
    git_url: https://github.com/ELEKTRONN/ELEKTRONN.git

requirements:
  build:
    - python <3
    - setuptools
    - cython
    - theano
    - h5py
    - matplotlib

  run:
    - python <3
    - theano
    - h5py
    - matplotlib

about:
  home: http://www.elektronn.org/
  license: GPL
