package:
  name: elektronn-git
  version: 'git'

source:
    git_url: https://github.com/ELEKTRONN/ELEKTRONN.git

requirements:
  build:
    - python 2.7*
    - setuptools
    - cython
    - theano
    - h5py
    - matplotlib

  run:
    - python =2.7*
    - theano
    - h5py
    - matplotlib

about:
  home: http://www.elektronn.org/
  license: GPLv3
  license_file: LICENSE.txt
